"""add authorized engagement workspaces

Revision ID: 79ca03174ce6
Revises: b536f285f7ae
Create Date: 2026-08-30 11:22:34.762027
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '79ca03174ce6'
down_revision: Union[str, Sequence[str], None] = 'b536f285f7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('client_name', sa.String(length=160), nullable=True),
    sa.Column('engagement_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('scope_rules', sa.Text(), nullable=False),
    sa.Column('authorization_basis', sa.String(length=48), nullable=False),
    sa.Column('authorization_attestation', sa.String(length=600), nullable=False),
    sa.Column('authorization_confirmed', sa.Boolean(), nullable=False),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorization_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('selected_teams', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_engagement_org_status_updated', 'engagements', ['organization_id', 'status', 'updated_at'], unique=False)
    op.create_table('engagement_targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=180), nullable=False),
    sa.Column('locator', sa.Text(), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('scope_status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_engagement_target_org_engagement', 'engagement_targets', ['organization_id', 'engagement_id'], unique=False)
    op.create_table('assessment_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('baseline_run_id', sa.String(length=36), nullable=True),
    sa.Column('team_plan', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['baseline_run_id'], ['assessment_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'sequence', name='uq_assessment_run_engagement_sequence')
    )
    op.create_index('ix_assessment_run_org_status', 'assessment_runs', ['organization_id', 'status'], unique=False)
    op.create_table('engagement_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_run_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('media_kind', sa.String(length=32), nullable=False),
    sa.Column('analysis_status', sa.String(length=32), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_run_id'], ['assessment_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', name='uq_engagement_asset_evidence')
    )
    op.create_index('ix_engagement_asset_org_engagement', 'engagement_assets', ['organization_id', 'engagement_id'], unique=False)
    with op.batch_alter_table('findings') as batch_op:
        batch_op.add_column(sa.Column('engagement_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('assessment_run_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('fingerprint', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('owner_team', sa.String(length=24), nullable=True))
        batch_op.create_index('ix_finding_engagement_run', ['engagement_id', 'assessment_run_id'], unique=False)
        batch_op.create_index('ix_findings_fingerprint', ['fingerprint'], unique=False)
        batch_op.create_foreign_key('fk_findings_engagement', 'engagements', ['engagement_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_findings_assessment_run', 'assessment_runs', ['assessment_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings') as batch_op:
        batch_op.drop_constraint('fk_findings_assessment_run', type_='foreignkey')
        batch_op.drop_constraint('fk_findings_engagement', type_='foreignkey')
        batch_op.drop_index('ix_findings_fingerprint')
        batch_op.drop_index('ix_finding_engagement_run')
        batch_op.drop_column('owner_team')
        batch_op.drop_column('fingerprint')
        batch_op.drop_column('assessment_run_id')
        batch_op.drop_column('engagement_id')
    op.drop_index('ix_engagement_asset_org_engagement', table_name='engagement_assets')
    op.drop_table('engagement_assets')
    op.drop_index('ix_assessment_run_org_status', table_name='assessment_runs')
    op.drop_table('assessment_runs')
    op.drop_index('ix_engagement_target_org_engagement', table_name='engagement_targets')
    op.drop_table('engagement_targets')
    op.drop_index('ix_engagement_org_status_updated', table_name='engagements')
    op.drop_table('engagements')
    # ### end Alembic commands ###
