"""initial tenant security platform

Revision ID: b536f285f7ae
Revises:
Create Date: 2026-08-30 03:08:34.844479
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b536f285f7ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('safety_level', sa.String(length=24), nullable=False),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=False),
    sa.Column('audit_head', sa.String(length=64), nullable=False),
    sa.Column('audit_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_policies',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('default_disposition', sa.String(length=24), nullable=False),
    sa.Column('sensitive_data_disposition', sa.String(length=24), nullable=False),
    sa.Column('approved_vendors', sa.JSON(), nullable=False),
    sa.Column('approved_domains', sa.JSON(), nullable=False),
    sa.Column('blocked_domains', sa.JSON(), nullable=False),
    sa.Column('prohibited_data_labels', sa.JSON(), nullable=False),
    sa.Column('retain_prompt_content', sa.Boolean(), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash'),
    sa.UniqueConstraint('organization_id', 'sequence', name='uq_audit_org_sequence')
    )
    op.create_index('ix_audit_org_created', 'audit_events', ['organization_id', 'created_at'], unique=False)
    op.create_table('connectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_connector_org_name'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_connectors_organization_id'), 'connectors', ['organization_id'], unique=False)
    op.create_index(op.f('ix_connectors_token_prefix'), 'connectors', ['token_prefix'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('commander_user_id', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['commander_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incident_org_status', 'incidents', ['organization_id', 'status'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('invited_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_invitation_org_status', 'invitations', ['organization_id', 'status'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_membership_org_user')
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=96), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_status_available', 'outbox_events', ['status', 'available_at'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('current_state', sa.String(length=64), nullable=False),
    sa.Column('marking', sa.String(length=64), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_program_org_slug')
    )
    op.create_index(op.f('ix_programs_organization_id'), 'programs', ['organization_id'], unique=False)
    op.create_table('retention_policies',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('telemetry_days', sa.Integer(), nullable=False),
    sa.Column('task_days', sa.Integer(), nullable=False),
    sa.Column('evidence_days', sa.Integer(), nullable=False),
    sa.Column('audit_days', sa.Integer(), nullable=False),
    sa.Column('legal_hold_default', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('security_controls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('control_key', sa.String(length=96), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('owner_team', sa.String(length=24), nullable=False),
    sa.Column('objective', sa.String(length=600), nullable=False),
    sa.Column('modes', sa.JSON(), nullable=False),
    sa.Column('required_source', sa.String(length=96), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'control_key', name='uq_security_control_org_key')
    )
    op.create_index('ix_security_control_org_team', 'security_controls', ['organization_id', 'owner_team'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_id', 'external_id', name='uq_agent_connector_external')
    )
    op.create_index('ix_agent_org_status', 'agents', ['organization_id', 'status'], unique=False)
    op.create_table('ai_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=180), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('disposition', sa.String(length=24), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('user_ref_hash', sa.String(length=64), nullable=True),
    sa.Column('device_ref_hash', sa.String(length=64), nullable=True),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('mcp_servers', sa.JSON(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source', 'external_id', name='uq_ai_asset_source_external')
    )
    op.create_index('ix_ai_asset_org_disposition', 'ai_assets', ['organization_id', 'disposition'], unique=False)
    op.create_index('ix_ai_asset_org_last_seen', 'ai_assets', ['organization_id', 'last_seen_at'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finding_org_status_severity', 'findings', ['organization_id', 'status', 'severity'], unique=False)
    op.create_table('ai_usage_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('destination_domain', sa.String(length=253), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('bytes_sent', sa.Integer(), nullable=False),
    sa.Column('bytes_received', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_microusd', sa.Integer(), nullable=False),
    sa.Column('data_labels', sa.JSON(), nullable=False),
    sa.Column('policy_action', sa.String(length=24), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['ai_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'connector_id', 'idempotency_key', name='uq_ai_usage_connector_key')
    )
    op.create_index('ix_ai_usage_org_occurred', 'ai_usage_events', ['organization_id', 'occurred_at'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=True),
    sa.Column('connector_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('lease_token_hash', sa.String(length=64), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_connector_status', 'tasks', ['connector_id', 'status'], unique=False)
    op.create_index('ix_task_org_status_created', 'tasks', ['organization_id', 'status', 'created_at'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=96), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'connector_id', 'idempotency_key', name='uq_event_org_connector_key')
    )
    op.create_index('ix_event_org_occurred', 'telemetry_events', ['organization_id', 'occurred_at'], unique=False)
    op.create_index('ix_event_org_type', 'telemetry_events', ['organization_id', 'event_type'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('decided_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=600), nullable=False),
    sa.Column('decision_note', sa.String(length=600), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_org_status', 'approvals', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_approvals_task_id'), 'approvals', ['task_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('connector_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=240), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('storage_key', sa.String(length=320), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=48), nullable=False),
    sa.Column('scan_status', sa.String(length=24), nullable=False),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_evidence_org_created', 'evidence', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_evidence_org_sha', 'evidence', ['organization_id', 'sha256'], unique=False)
    op.create_table('policy_violations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('usage_event_id', sa.String(length=36), nullable=True),
    sa.Column('rule_id', sa.String(length=96), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('disposition', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.String(length=600), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['ai_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usage_event_id'], ['ai_usage_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_violation_org_created', 'policy_violations', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_violation_org_status', 'policy_violations', ['organization_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_violation_org_status', table_name='policy_violations')
    op.drop_index('ix_violation_org_created', table_name='policy_violations')
    op.drop_table('policy_violations')
    op.drop_index('ix_evidence_org_sha', table_name='evidence')
    op.drop_index('ix_evidence_org_created', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_approvals_task_id'), table_name='approvals')
    op.drop_index('ix_approval_org_status', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_event_org_type', table_name='telemetry_events')
    op.drop_index('ix_event_org_occurred', table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index('ix_task_org_status_created', table_name='tasks')
    op.drop_index('ix_task_connector_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_ai_usage_org_occurred', table_name='ai_usage_events')
    op.drop_table('ai_usage_events')
    op.drop_index('ix_finding_org_status_severity', table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_ai_asset_org_last_seen', table_name='ai_assets')
    op.drop_index('ix_ai_asset_org_disposition', table_name='ai_assets')
    op.drop_table('ai_assets')
    op.drop_index('ix_agent_org_status', table_name='agents')
    op.drop_table('agents')
    op.drop_index('ix_security_control_org_team', table_name='security_controls')
    op.drop_table('security_controls')
    op.drop_table('retention_policies')
    op.drop_index(op.f('ix_programs_organization_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index('ix_outbox_status_available', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_invitation_org_status', table_name='invitations')
    op.drop_table('invitations')
    op.drop_index('ix_incident_org_status', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_connectors_token_prefix'), table_name='connectors')
    op.drop_index(op.f('ix_connectors_organization_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index('ix_audit_org_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('ai_policies')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
